name: Federated Learning poisoning attack testbed
server:
  num-round: 30
  clients: 1
  mode: fedavg
  hyper-detection:
    enable: False
    cosine-search: 10
    n_components: 3
    eps: 0.015
    min_samples: 3
  model: TransformerModel
  data-name: ICU
  parameters:
    load: True
  validation: True
  data-distribution:
    num-data-range:
      - 5000
      - 5000
  genuine-rate: 0.5
  random-seed: 1

rabbit:
  address: 127.0.0.1
  username: admin
  password: admin

log_path: .

learning:
  epoch: 1
  learning-rate: 0.001
  hyper-lr: 0.001
  momentum: 0.5
  batch-size: 64
  clip-grad-norm: 50.0
