name: Federated Learning poisoning attack testbed
server:
  num-round: 50
  clients: 1
  mode: FLTrust # hyper
  hyper-detection:
    enable: False
    cosine-search: 10
    n_components: 3
    eps: 0.015
    min_samples: 3
  model: TransformerModel
  data-name: ICU
  parameters:
    load: True
  validation: True
  data-distribution:
    num-data-range:
      - 0
      - 500
  genuine-rate: 0.5
  random-seed: 1

rabbit:
  address: 127.0.0.1
  username: thuong 
  password: thuong

log_path: .

learning:
  epoch: 1
  learning-rate: 0.0005
  hyper-lr: 0.0005
  momentum: 0.5
  batch-size: 128
  clip-grad-norm: 0.0
