name: Federated Learning poisoning attack testbed
server:
  num-round: 50
  clients: 30
  mode: hyper
  model: Transformer
  data-name: ICU
  parameters:
    load: True
  validation: True
  data-distribution:
    num-data-range:
      - 100
      - 100
  random-seed: 1

rabbit:
  address: 127.0.0.1
  username: admin
  password: admin

log_path: .

learning:
  epoch: 5
  learning-rate: 0.0005
  hyper-lr: 0.0005
  momentum: 0.5
  batch-size: 128
